{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "import torch\n",
    "import random\n",
    "import pandas as pd\n",
    "import json\n",
    "\n",
    "from torch.utils.data import Dataset\n",
    "\n",
    "import torch\n",
    "import random\n",
    "import numpy as np\n",
    "import torch.backends.cudnn as cudnn\n",
    "\n",
    "from tqdm import tqdm\n",
    "from collections import defaultdict\n",
    "\n",
    "from torch.optim import AdamW\n",
    "from torch.utils.data import DataLoader\n",
    "from torch.nn import CosineEmbeddingLoss\n",
    "\n",
    "from sentence_transformers import SentenceTransformer, InputExample, losses\n",
    "from sklearn.metrics.pairwise import cosine_similarity"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "device: cuda:0\n"
     ]
    }
   ],
   "source": [
    "seed = 42\n",
    "torch.manual_seed(seed)\n",
    "torch.cuda.manual_seed(seed)\n",
    "torch.cuda.manual_seed_all(seed)\n",
    "np.random.seed(seed)\n",
    "cudnn.benchmark = False\n",
    "cudnn.deterministic = True\n",
    "random.seed(seed)\n",
    "# seed 결과가달라짐 3~4%\n",
    "\n",
    "device = \"cuda:0\" if torch.cuda.is_available() else \"cpu\"\n",
    "print('device:', device)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "----------\n",
      "Data Loading Start!!\n",
      "----------\n",
      "origin_data: (12816, 4)\n",
      "Training Data Amount: 323317\n",
      "----------\n",
      "Data Loading Complete!!\n",
      "----------\n"
     ]
    }
   ],
   "source": [
    "print('-'*10)\n",
    "print('Data Loading Start!!')\n",
    "print('-'*10)\n",
    "\n",
    "## dataset class\n",
    "path = \"/data/ephemeral/home/data/aug_data.jsonl\"\n",
    "\n",
    "with open(path) as f:\n",
    "    data = [json.loads(line) for line in f]\n",
    "data = pd.DataFrame(data)\n",
    "print('origin_data:', data.shape)\n",
    "\n",
    "query = []\n",
    "doc = []\n",
    "label = []\n",
    "for i, (q, d, domain) in enumerate(zip(list(data['question']), list(data['content']), list(data['domain']))): # Domain = 주제\n",
    "    if type(q) != str: continue\n",
    "    if type(d) != str: continue            \n",
    "\n",
    "    same_domain_desc_list = pd.unique(data[data['domain']==domain]['content'])\n",
    "    other_domain_desc_list =  pd.unique(data[data['domain']!=domain]['content'])\n",
    "\n",
    "    # Positive Pair\n",
    "    query.append(q)\n",
    "    doc.append(d)\n",
    "    label.append(1)\n",
    "\n",
    "    # Negative Pair\n",
    "        # Hard\n",
    "    negative_sample_count = 20 if len(same_domain_desc_list) >= 20 else len(same_domain_desc_list)\n",
    "    desc_list_sample = random.sample(list(same_domain_desc_list), k=negative_sample_count)\n",
    "    for dl in desc_list_sample:\n",
    "        if d == dl: continue\n",
    "        else: \n",
    "            query.append(q)\n",
    "            doc.append(dl)\n",
    "            label.append(-1)\n",
    "        \n",
    "        # Soft\n",
    "    other_desc_list_sample = random.sample(list(other_domain_desc_list), 5)\n",
    "    for dl in other_desc_list_sample:\n",
    "        query.append(q)\n",
    "        doc.append(dl)\n",
    "        label.append(-1)\n",
    "            \n",
    "# query, doc 및 label 리스트를 사용하여 train_examples 생성\n",
    "train_dataset = []\n",
    "for q, d, l in zip(query, doc, label):\n",
    "    train_dataset.append(InputExample(texts=[q, d], label=float(l)))\n",
    "print('Training Data Amount:', len(train_dataset))\n",
    "\n",
    "print('-'*10)\n",
    "print('Data Loading Complete!!')\n",
    "print('-'*10)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[<sentence_transformers.readers.InputExample.InputExample at 0x7ff69c32f460>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c32f400>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c32f100>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c32f190>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c32f1c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c32f430>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c32f4c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c32f2b0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c32f550>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c32f5b0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c32f610>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c32f670>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c32f6d0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c32f730>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c32f790>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c32f7f0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c32f850>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff6a03f19f0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff6a03f1f90>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff6a03f17b0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff6a03f1de0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff6a03f2200>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff6a03f1c90>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff6a03f1e10>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff6a03f2020>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff6a03f3070>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff6a03f0460>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff6a03f2350>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff6a03f1ae0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff6a03f2d10>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff6a03f23e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff6a03f1e70>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff6a03f1b70>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff6a03f1ed0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff6a03f2410>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff6a03f1b40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff6a03f2c20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff6a03f2590>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff6a03f3160>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff6a03f1ea0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff7d62df520>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff7d62de920>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff7d62dec20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff7d62df6a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff7d62de680>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff7d62dec80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff7d62dec50>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff7d69a1000>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff7d69a0dc0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff7d69a1060>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff7d69a1090>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff7d69a0e20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff7d69a0f40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff7d69a1030>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff7d69a1120>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff7d69a13f0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff7d69a03d0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff6a0332c20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff6a0331420>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff6a0332140>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c45e890>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c45e6b0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c45e860>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69f51a110>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69f51a6b0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed8040>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed80a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed8100>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed8160>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed81c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed8220>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed8280>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed82e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed8340>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed83a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed8400>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed8460>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed84c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed8520>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed8580>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed85e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed8640>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed86a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed8700>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed8760>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed87c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed8820>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed8880>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed88e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed8940>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed89a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed8a00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed8a60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed8ac0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed8b20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed8b80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed8be0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed8c40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed8ca0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed8d00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed8d60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed8dc0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed8e20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed8e80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed8ee0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed8f40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed8fa0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed9000>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed9060>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed90c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed9120>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed9180>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed91e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed9240>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed92a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed9300>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed9360>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed93c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed9420>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed9480>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed94e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed9540>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed95a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed9600>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed9660>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed96c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed9720>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed9780>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed97e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed9840>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed98a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed9900>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed9960>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed99c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed9a20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed9a80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed9ae0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed9b40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed9ba0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed9c00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed9c60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed9cc0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed9d20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed9d80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed9de0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed9e40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed9ea0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed9f00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed9f60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bed9fc0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68beda020>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68beda080>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68beda0e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68beda140>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68beda1a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68beda200>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68beda260>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68beda2c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68beda320>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68beda380>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68beda3e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68beda440>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68beda4a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68beda500>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68beda560>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68beda5c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68beda620>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68beda680>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68beda6e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68beda740>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68beda7a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68beda800>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68beda860>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68beda8c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68beda920>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68beda980>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68beda9e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedaa40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedaaa0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedab00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedab60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedabc0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedac20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedac80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedace0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedad40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedada0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedae00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedae60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedaec0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedaf20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedaf80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedafe0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedb040>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedb0a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedb100>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedb160>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedb1c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedb220>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedb280>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedb2e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedb340>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedb3a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedb400>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedb460>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedb4c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedb520>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedb580>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedb5e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedb640>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedb6a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedb700>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedb760>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedb7c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedb820>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedb880>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedb8e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedb940>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedb9a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedba00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedba60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedbac0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedbb20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedbb80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedbbe0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedbc40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedbca0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedbd00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedbd60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedbdc0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedbe20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedbe80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedbee0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedbf40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bedbfa0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef0040>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef00a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef0100>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef0160>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef01c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef0220>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef0280>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef02e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef0340>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef03a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef0400>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef0460>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef04c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef0520>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef0580>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef05e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef0640>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef06a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef0700>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef0760>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef07c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef0820>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef0880>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef08e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef0940>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef09a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef0a00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef0a60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef0ac0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef0b20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef0b80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef0be0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef0c40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef0ca0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef0d00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef0d60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef0dc0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef0e20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef0e80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef0ee0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef0f40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef0fa0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef1000>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef1060>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef10c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef1120>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef1180>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef11e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef1240>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef12a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef1300>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef1360>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef13c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef1420>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef1480>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef14e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef1540>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef15a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef1600>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef1660>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef16c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef1720>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef1780>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef17e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef1840>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef18a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef1900>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef1960>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef19c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef1a20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef1a80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef1ae0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef1b40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef1ba0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef1c00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef1c60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef1cc0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef1d20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef1d80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef1de0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef1e40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef1ea0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef1f00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef1f60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef1fc0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef2020>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef2080>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef20e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef2140>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef21a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef2200>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef2260>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef22c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef2320>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef2380>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef23e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef2440>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef24a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef2500>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef2560>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef25c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef2620>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef2680>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef26e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef2740>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef27a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef2800>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef2860>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef28c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef2920>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef2980>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef29e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef2a40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef2aa0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef2b00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef2b60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef2bc0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef2c20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef2c80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef2ce0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef2d40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef2da0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef2e00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef2e60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef2ec0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef2f20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef2f80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef2fe0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef3040>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef30a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef3100>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef3160>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef31c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef3220>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef3280>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef32e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef3340>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef33a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef3400>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef3460>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef34c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef3520>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef3580>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef35e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef3640>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef36a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef3700>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef3760>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef37c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef3820>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef3880>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef38e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef3940>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef39a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef3a00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef3a60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef3ac0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef3b20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef3b80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef3be0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef3c40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef3ca0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef3d00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef3d60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef3dc0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef3e20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef3e80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef3ee0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef3f40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef3fa0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef4040>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef40a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef4100>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef4160>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef41c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef4220>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef4280>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef42e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef4340>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef43a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef4400>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef4460>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef44c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef4520>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef4580>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef45e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef4640>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef46a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef4700>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef4760>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef47c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef4820>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef4880>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef48e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef4940>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef49a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef4a00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef4a60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef4ac0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef4b20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef4b80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef4be0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef4c40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef4ca0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef4d00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef4d60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef4dc0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef4e20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef4e80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef4ee0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef4f40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef4fa0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef5000>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef5060>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef50c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef5120>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef5180>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef51e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef5240>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef52a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef5300>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef5360>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef53c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef5420>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef5480>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef54e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef5540>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef55a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef5600>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef5660>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef56c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef5720>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef5780>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef57e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef5840>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef58a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef5900>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef5960>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef59c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef5a20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef5a80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef5ae0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef5b40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef5ba0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef5c00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef5c60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef5cc0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef5d20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef5d80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef5de0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef5e40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef5ea0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef5f00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef5f60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef5fc0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef6020>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef6080>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef60e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef6140>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef61a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef6200>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef6260>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef62c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef6320>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef6380>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef63e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef6440>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef64a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef6500>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef6560>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef65c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef6620>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef6680>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef66e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef6740>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef67a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef6800>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef6860>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef68c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef6920>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef6980>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef69e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef6a40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef6aa0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef6b00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef6b60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef6bc0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef6c20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef6c80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef6ce0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef6d40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef6da0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef6e00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef6e60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef6ec0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef6f20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef6f80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef6fe0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef7040>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef70a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef7100>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef7160>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef71c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef7220>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef7280>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef72e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef7340>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef73a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef7400>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef7460>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef74c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef7520>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef7580>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef75e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef7640>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef76a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef7700>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef7760>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef77c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef7820>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef7880>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef78e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef7940>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef79a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef7a00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef7a60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef7ac0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef7b20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef7b80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef7be0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef7c40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef7ca0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef7d00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef7d60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef7dc0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef7e20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef7e80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef7ee0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef7f40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff68bef7fa0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d8040>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d80a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d8100>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d8160>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d81c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d8220>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d8280>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d82e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d8340>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d83a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d8400>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d8460>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d84c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d8520>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d8580>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d85e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d8640>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d86a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d8700>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d8760>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d87c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d8820>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d8880>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d88e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d8940>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d89a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d8a00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d8a60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d8ac0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d8b20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d8b80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d8be0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d8c40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d8ca0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d8d00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d8d60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d8dc0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d8e20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d8e80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d8ee0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d8f40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d8fa0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d9000>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d9060>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d90c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d9120>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d9180>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d91e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d9240>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d92a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d9300>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d9360>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d93c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d9420>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d9480>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d94e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d9540>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d95a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d9600>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d9660>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d96c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d9720>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d9780>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d97e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d9840>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d98a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d9900>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d9960>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d99c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d9a20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d9a80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d9ae0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d9b40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d9ba0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d9c00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d9c60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d9cc0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d9d20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d9d80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d9de0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d9e40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d9ea0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d9f00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d9f60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0d9fc0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0da020>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0da080>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0da0e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0da140>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0da1a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0da200>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0da260>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0da2c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0da320>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0da380>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0da3e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0da440>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0da4a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0da500>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0da560>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0da5c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0da620>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0da680>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0da6e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0da740>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0da7a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0da800>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0da860>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0da8c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0da920>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0da980>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0da9e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0daa40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0daaa0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0dab00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0dab60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0dabc0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0dac20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0dac80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0dace0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0dad40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0dada0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0dae00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0dae60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0daec0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0daf20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0daf80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0dafe0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0db040>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0db0a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0db100>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0db160>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0db1c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0db220>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0db280>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0db2e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0db340>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0db3a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0db400>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0db460>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0db4c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0db520>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0db580>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0db5e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0db640>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0db6a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0db700>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0db760>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0db7c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0db820>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0db880>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0db8e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0db940>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0db9a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0dba00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0dba60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0dbac0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0dbb20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0dbb80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0dbbe0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0dbc40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0dbca0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0dbd00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0dbd60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0dbdc0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0dbe20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0dbe80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0dbee0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0dbf40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0dbfa0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ec040>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ec0a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ec100>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ec160>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ec1c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ec220>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ec280>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ec2e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ec340>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ec3a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ec400>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ec460>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ec4c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ec520>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ec580>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ec5e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ec640>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ec6a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ec700>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ec760>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ec7c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ec820>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ec880>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ec8e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ec940>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ec9a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0eca00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0eca60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ecac0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ecb20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ecb80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ecbe0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ecc40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ecca0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ecd00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ecd60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ecdc0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ece20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ece80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ecee0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ecf40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ecfa0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ed000>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ed060>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ed0c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ed120>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ed180>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ed1e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ed240>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ed2a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ed300>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ed360>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ed3c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ed420>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ed480>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ed4e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ed540>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ed5a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ed600>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ed660>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ed6c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ed720>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ed780>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ed7e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ed840>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ed8a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ed900>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ed960>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ed9c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0eda20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0eda80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0edae0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0edb40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0edba0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0edc00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0edc60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0edcc0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0edd20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0edd80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0edde0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ede40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0edea0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0edf00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0edf60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0edfc0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ee020>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ee080>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ee0e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ee140>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ee1a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ee200>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ee260>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ee2c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ee320>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ee380>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ee3e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ee440>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ee4a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ee500>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ee560>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ee5c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ee620>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ee680>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ee6e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ee740>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ee7a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ee800>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ee860>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ee8c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ee920>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ee980>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ee9e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0eea40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0eeaa0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0eeb00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0eeb60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0eebc0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0eec20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0eec80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0eece0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0eed40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0eeda0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0eee00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0eee60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0eeec0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0eef20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0eef80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0eefe0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ef040>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ef0a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ef100>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ef160>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ef1c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ef220>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ef280>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ef2e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ef340>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ef3a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ef400>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ef460>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ef4c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ef520>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ef580>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ef5e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ef640>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ef6a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ef700>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ef760>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ef7c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ef820>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ef880>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ef8e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ef940>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0ef9a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0efa00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0efa60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0efac0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0efb20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0efb80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0efbe0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0efc40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0efca0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0efd00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0efd60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0efdc0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0efe20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0efe80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0efee0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0eff40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0effa0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f8040>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f80a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f8100>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f8160>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f81c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f8220>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f8280>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f82e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f8340>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f83a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f8400>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f8460>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f84c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f8520>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f8580>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f85e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f8640>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f86a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f8700>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f8760>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f87c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f8820>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f8880>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f88e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f8940>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f89a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f8a00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f8a60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f8ac0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f8b20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f8b80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f8be0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f8c40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f8ca0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f8d00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f8d60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f8dc0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f8e20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f8e80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f8ee0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f8f40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f8fa0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f9000>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f9060>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f90c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f9120>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f9180>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f91e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f9240>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f92a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f9300>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f9360>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f93c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f9420>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f9480>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f94e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f9540>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f95a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f9600>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f9660>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f96c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f9720>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f9780>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f97e0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f9840>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f98a0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f9900>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f9960>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f99c0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f9a20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f9a80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f9ae0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f9b40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f9ba0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f9c00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f9c60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f9cc0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f9d20>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f9d80>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f9de0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f9e40>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f9ea0>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f9f00>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f9f60>,\n",
       " <sentence_transformers.readers.InputExample.InputExample at 0x7ff69c0f9fc0>,\n",
       " ...]"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "train_dataset"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/opt/conda/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1617: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be deprecated in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "----------\n",
      "Training Start!!\n",
      "----------\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Iteration: 100%|██████████| 20208/20208 [38:55<00:00,  8.65it/s]\n",
      "Epoch: 100%|██████████| 1/1 [38:55<00:00, 2335.63s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "----------\n",
      "Training Complete!!\n",
      "----------\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "model = SentenceTransformer(\"jhgan/ko-sroberta-multitask\")\n",
    "\n",
    "## data loader\n",
    "batch_size = 16\n",
    "train_dataloader = DataLoader(train_dataset, shuffle=True, batch_size=batch_size)\n",
    "\n",
    "## loss \n",
    "train_loss = losses.CosineSimilarityLoss(model)\n",
    "\n",
    "print('-'*10)\n",
    "print('Training Start!!')\n",
    "print('-'*10)\n",
    "\n",
    "# Tune the model\n",
    "model.fit(train_objectives=[(train_dataloader, train_loss)], epochs=1, warmup_steps=100)\n",
    "        \n",
    "print('-'*10)\n",
    "print('Training Complete!!')\n",
    "print('-'*10)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Embedding: [-0.8951695  -0.01308854  0.53727984 -0.38678288  0.25949168]...\n"
     ]
    }
   ],
   "source": [
    "sentence = \"에너지 균형을 유지하는 것이 건강에 어떤 영향을 미치나요?\"\n",
    "embedding = model.encode(sentence)\n",
    "print(f\"Embedding: {embedding[:5]}...\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [],
   "source": [
    "model_path = './sroberta_finetuned_epoch_1'\n",
    "model.save(model_path)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
